services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
    - "127.0.0.1:5432:5432"
    volumes:
    - ./data/postgres:/var/lib/postgresql/data
    shm_size: 512MB
