services:
  officeplanner:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - "./data/officeplanner:/root/.aspnet"
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    shm_size: 512MB
