FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /app
COPY *.sln .
COPY OfficePlanner/*.csproj ./OfficePlanner/

RUN dotnet restore
RUN cd OfficePlanner && dotnet restore

COPY . .
RUN dotnet build

ENTRYPOINT ["dotnet", "watch", "--project", "OfficePlanner"]
