services:
  officeplanner:
    build: .
    ports:
    - "8080:8080"
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
    - ./data:/var/lib/postgresql/data
    shm_size: 512MB
