name: ci

on:
  push:
    branches: ["master"]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker build . -t officeplanner
        docker tag officeplanner ghcr.io/trolldemorted/officeplanner/officeplanner:nightly
        docker push ghcr.io/trolldemorted/officeplanner/officeplanner:nightly
